# Generated by Django 5.2.8 on 2025-11-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text="e.g., 'fas fa-piggy-bank' from Font Awesome", max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='capsule',
            options={'ordering': ['topic__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='category',
        ),
        migrations.AlterField(
            model_name='capsule',
            name='back_content',
            field=models.TextField(help_text='Content for the back of the flip card.'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='front_content',
            field=models.TextField(help_text='Content for the front of the flip card.'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of capsules within a topic (Day 1, Day 2, etc.).'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of topics within a subject.')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.subject')),
            ],
            options={
                'ordering': ['subject__name', 'order'],
            },
        ),
        migrations.AddField(
            model_name='capsule',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='learning.topic'),
            preserve_default=False,
        ),
    ]
