# Generated by Django 5.2.8 on 2025-11-08 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_subject_alter_capsule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
